function OAS_RICH(position) {
if (position == 'Right1') {
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('		\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('<script type="text/javascript">\n');
document.write ('//<![CDATA[\n');
document.write ('var filePath                     = "http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-MH-biology-direct-LB/Biology_Direct_Skyscraper_160x600px_v3.swf/1292425416";\n');
document.write ('var TFSMFlash_PRETAG             = "";\n');
document.write ('var TFSMFlash_POSTTAG            = "";\n');
document.write ('var TFSMFlash_VERSION            = "8";\n');
document.write ('var TFSMFlash_WMODE              = "window";\n');
document.write ('\n');
document.write ('			var TFSMFlash_OASCLICK           = "http://oas.biomedcentral.com/5c/gigasciencejournal.com/about/L28/1664364877/Right1/biomed/House-MH-biology-direct-LB/House-MH-biology-direct-S.html/7776357a494650483044514141654179";\n');
document.write ('	\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE   = "?clickTAG="+TFSMFlash_OASCLICK + "";\n');
document.write ('var TFSMFlash_SWFFILE            = filePath + TFSMFlash_SWFCLICKVARIABLE;\n');
document.write ('var TFSMFlash_FSCOMMAND          = "";\n');
document.write ('var TFSMFlash_IMAGEALTERNATE     = "http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-MH-biology-direct-LB/Biology_Direct_Skyscraper_160x600px_v3.gif/1292425416";\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_OASALTTEXT         = "";\n');
document.write ('var TFSMFlash_OASTARGET          = "_blank";\n');
document.write ('var TFSMFlash_OASPROTOCOL        = "http://";\n');
document.write ('var TFSMFlash_OASDIM             = "width=');
document.write ("'");
document.write ('160px');
document.write ("'");
document.write (' height=');
document.write ("'");
document.write ('600px');
document.write ("'");
document.write ('";\n');
document.write ('var TFSMFlash_OASADID            = "OAS_RMF_Right1_FLASH";\n');
document.write ('document.write("<"+"scr"+"ipt type=\\');
document.write ('"text/javascript\\');
document.write ('" src=\\');
document.write ('"http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-MH-biology-direct-LB/TFSMFlashWrapper301.js/1292425416\\');
document.write ('"><\\');
document.write ('/scr"+"ipt"+">");\n');
document.write ('//]]>\n');
document.write ('</script>\n');
document.write ('\n');
document.write ('<noscript>\n');
document.write ('	<a href="http://oas.biomedcentral.com/5c/gigasciencejournal.com/about/L28/1664364877/Right1/biomed/House-MH-biology-direct-LB/House-MH-biology-direct-S.html/7776357a494650483044514141654179" target="_blank">\n');
document.write ('		<img src="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-MH-biology-direct-LB/Biology_Direct_Skyscraper_160x600px_v3.gif/1292425416" width="160" height="600" alt="" style="border:0px black solid;" />\n');
document.write ('	</a>\n');
document.write ('</noscript>\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
}
if (position == 'Top') {
document.write ('\n');
document.write ('<SCRIPT type="text/javascript"> \n');
document.write ('var TFSMFlash_PRETAG="";\n');
document.write ('var TFSMFlash_POSTTAG=""; \n');
document.write ('var TFSMFlash_VERSION="7"; \n');
document.write ('var TFSMFlash_WMODE="window"; \n');
document.write ('var TFSMFlash_OASCLICK="http://oas.biomedcentral.com/5c/gigasciencejournal.com/about/L28/2055432490/Top/biomed/House-SR-gsejournal-CFP-Submit-LB/House-SR-gsejournal-CFP-Submit-LB.html/7776357a494650483044514141654179";\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE="?clickTag="+TFSMFlash_OASCLICK ; \n');
document.write ('var TFSMFlash_SWFFILE="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SR-gsejournal-CFP-Submit-LB/Genetics_Selection_Evolution_Leaderboard_dynamic.swf/1272550441"+TFSMFlash_SWFCLICKVARIABLE; \n');
document.write ('var TFSMFlash_FSCOMMAND=""; \n');
document.write ('var TFSMFlash_IMAGEALTERNATE="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SR-gsejournal-CFP-Submit-LB/Genetics_Selection_Evolution_Leaderboard_v1.gif/1272550441"; \n');
document.write ('var TFSMFlash_OASALTTEXT=""; \n');
document.write ('var TFSMFlash_OASTARGET="_blank"; \n');
document.write ('var TFSMFlash_OASPROTOCOL="http://"; \n');
document.write ('var TFSMFlash_OASDIM="WIDTH=');
document.write ("'");
document.write ('728');
document.write ("'");
document.write (' HEIGHT=');
document.write ("'");
document.write ('90');
document.write ("'");
document.write ('"; \n');
document.write ('var TFSMFlash_OASADID="OAS_RMF_Top_FLASH"; \n');
document.write ('document.write(');
document.write ("'");
document.write ('<scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt src="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SR-gsejournal-CFP-Submit-LB/TFSMFlashWrapper204.js/1272550441"></scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt>');
document.write ("'");
document.write ('); \n');
document.write ('</SCRIPT>\n');
document.write ('\n');
document.write ('<NOSCRIPT>\n');
document.write ('<A HREF="http://oas.biomedcentral.com/5c/gigasciencejournal.com/about/L28/2055432490/Top/biomed/House-SR-gsejournal-CFP-Submit-LB/House-SR-gsejournal-CFP-Submit-LB.html/7776357a494650483044514141654179" TARGET="_blank"><IMG SRC="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SR-gsejournal-CFP-Submit-LB/Genetics_Selection_Evolution_Leaderboard_v1.gif/1272550441" WIDTH=');
document.write ("'");
document.write ('728');
document.write ("'");
document.write (' HEIGHT=');
document.write ("'");
document.write ('90');
document.write ("'");
document.write (' BORDER=0 ALT=""></a>\n');
document.write ('</NOSCRIPT>\n');
document.write ('\n');
}
}
